# docker-compose.yml
# Placeholder for docker-compose setup

version: '3.8'
services:
  backend:
    build: .
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  frontend:
    build: .
    command: streamlit run frontend/streamlit_app.py --server.port 8501
    ports:
      - "8501:8501"
    depends_on:
      - backend 